In [1]:
import pandas as pd 
df = pd.read_csv("customers-100.csv")
df

Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1       2  1Ef7b82A4CAAD10    Preston    Lozano   
2       3  6F94879bDAfE5a6        Roy     Berry   
3       4  5Cef8BFA16c5e3c      Linda     Olsen   
4       5  053d585Ab6b3159     Joanna    Bender   
..    ...              ...        ...       ...   
95     96  cb8E23e48d22Eae       Karl     Greer   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson   
97     98  28CDbC0dFe4b1Db       Fred    Guerra   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer   
99    100  2354a0E336A91A1   Clarence    Haynes   

                            Company               City  \
0                   Rasmussen Group       East Leonard   
1                       Vega-Gentry  East Jimmychester   
2                     Murillo-Perry      Isabelborough   
3   Dominguez, Mcmillan and Donovan         Bensonview   
4          Martin, Lang and Andrade     West Priscilla   
..                              ...                ...   
95                        Carey LLC       East Richard   
96            Ware, Burns and Oneal       New Bradview   
97                    Schmitt-Jones         Ortegaland   
98               Fitzgerald-Harrell    Lake Elijahview   
99               Le, Nash and Cross          Judymouth   

                       Country                 Phone 1  \
0                        Chile            229.077.5154   
1                     Djibouti              5153435776   
2          Antigua and Barbuda         +1-539-402-0259   
3           Dominican Republic  001-808-617-6467x12895   
4   Slovakia (Slovak Republic)  001-234-203-0635x76146   
..                         ...                     ...   
95                      Guyana     (188)169-1674x58692   
96                   Sri Lanka         +1-846-706-2218   
97             Solomon Islands    +1-753-067-8419x7170   
98                       Aruba           (530)311-9786   
99                    Honduras           (753)813-6941   

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24   
1         686-620-1820x944                 vmata@colon.com        2021-04-23   
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25   
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02   
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17   
..                     ...                             ...               ...   
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30   
96            605.413.3198               vkemp@ferrell.com        2021-07-10   
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18   
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11   
99            783.639.1472          colleen91@faulkner.biz        2020-03-11   

                              Website  
0          http://www.stephenson.com/  
1               http://www.hobbs.com/  
2            http://www.lawrence.com/  
3          http://www.good-lyons.com/  
4         https://goodwin-ingram.com/  
..                                ...  
95            http://hayes-perez.com/  
96         https://novak-allison.com/  
97              https://www.ross.com/  
98               http://watkins.info/  
99  http://www.hatfield-saunders.net/  

[100 rows x 12 columns]

In [3]:
import pandas as pd
dataset=pd.read_csv("Salary_Data.csv")
dataset

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [15]:
dataset.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [9]:
dataset.head(10)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0
5              2.9  56642.0
6              3.0  60150.0
7              3.2  54445.0
8              3.2  64445.0
9              3.7  57189.0

In [11]:
dataset.tail()

YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [13]:
dataset.tail(10)

YearsExperience    Salary
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [19]:
import os 
os.getcwd()

'C:\\Users\\Omkar\\Desktop'

In [23]:
import numpy as np
a=np.zeros(3)
a

array([0., 0., 0.])

In [25]:
type(a)

numpy.ndarray

In [27]:
type(a[0])

numpy.float64

In [29]:
z=np.zeros(10)

In [31]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
z.shape

(10,)

In [41]:
z.shape=(10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [43]:
z=np.ones(10)

In [45]:
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [47]:
type(z[0])

numpy.float64

In [53]:
z=np.empty(3)
z


array([1.48540335e-311, 0.00000000e+000, 4.94065646e-324])

In [59]:
z=np.linspace(2,10,5)
z

array([ 2.,  4.,  6.,  8., 10.])

In [61]:
z=np.linspace(1,9,5)
z

array([1., 3., 5., 7., 9.])

In [63]:
z=np.array([10,20])
z

array([10, 20])

In [ ]:
matplotlib